### ISSUE TITLE
`npm run build` does not exit

### ISSUE THREAD

**Issue by azuwis** [rixo/svelte-template-hot#5] opened 2020-07-15 16:16 UTC
Steps to reproduce:
``` bash
npx degit rixo/svelte-template-hot test
cd test
npm install
npm run build
```

And then the build process does not exit.

I believe commit 0b50fc11db1e3eb156e70b3700676032e92f6a80 is related.

**Comment by rixo** [comment] 2020-07-16 11:47
Thanks for reporting.

It should be fixed in the last version of the template.

We don't want to completely exclude the hot plugin like was done before the commit you referenced, because ES HMR syntax (`import.meta.hot`) is not understood by some other Rollup plugins (namely `terser` in the template). `compatModuleHot` option rewrites `import.meta.hot` to `module.hot` (i.e. Webpack HMR syntax) that has been around for a much longer time and tends to be better supported in the ecosystem.

Anyway, the hot plugin is not supposed to fire its server in non watch mode, which was the problem and should now be fixed.

I was able to reproduce the issue and I'm confident it is fixed now, so I'm closing the issue. Feel free to reopen if it doesn't work for you.

**Closed as completed by rixo** 2020-07-16 11:47 UTC
